**ORACLE**

-- Criação da tabela CLIENTEPESSOAFISICA
CREATE TABLE clientepessoafisica (
    Idclientepessoafisica NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
    Nome VARCHAR2(255),
    RG CHAR(10) NOT NULL, 
    CPF CHAR(11) NOT NULL,
    Datadenascimento DATE,
    Telefone VARCHAR2(45),
    PRIMARY KEY (Idclientepessoafisica),
    CONSTRAINT unique_CPF_clientepessoafisica UNIQUE (CPF),
    CONSTRAINT unique_RG_clientepessoafisica UNIQUE (RG)
);

-- Inserção de dados na tabela CLIENTEPESSOAFISICA
INSERT INTO clientepessoafisica (Nome, RG, CPF, Datadenascimento, Telefone)
VALUES 
    ('Fulado de tal 1', '2654712412', '12457841545', TO_DATE('1992-05-22', 'YYYY-MM-DD'), '249998-7541'),
    ('Fulado de tal 2', '21456788945', '12456987451', TO_DATE('1990-04-21', 'YYYY-MM-DD'), '249998-7545'),
    ('Fulado de tal 3', '12457899452', '12459687412', TO_DATE('1991-02-20', 'YYYY-MM-DD'), '249998-7542'),
    ('Fulado de tal 4', '21469874312', '12456974384', TO_DATE('1995-01-19', 'YYYY-MM-DD'), '249998-7543')
;

-- Criação da tabela CLIENTEPESSOAJURIDICA
CREATE TABLE clientepessoajuridica (
    Idclientepessoajuridica NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
    Razaosocial VARCHAR2(255),
    Nomefantasia VARCHAR2(255),
    CNPJ CHAR(14) NOT NULL,
    Telefone VARCHAR2(45),
    PRIMARY KEY (Idclientepessoajuridica),
    CONSTRAINT unique_CNPJ_clientepessoajuridica UNIQUE (CNPJ)
);

-- Inserção de dados na tabela CLIENTEPESSOAJURIDICA
INSERT INTO clientepessoajuridica (Razaosocial, Nomefantasia, CNPJ, Telefone)
VALUES 
    ('Empresa 1 LTDA', 'Nome Fantasia 1', '12459745123456', '249945-7541'),
    ('Empresa 2 LTDA', 'Nome Fantasia 2', '54789412541021', '249945-5478'),
    ('Empresa 3 LTDA', 'Nome Fantasia 3', '10245789441212','249945-7845')
;

-- Criação da tabela VEICULO
CREATE TABLE veiculo (
    Idveiculo NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Marca VARCHAR2(255) NOT NULL,
    Modelo VARCHAR2(255) NOT NULL,
    Ano CHAR(4),
    Placa VARCHAR2(10),
    PRIMARY KEY (Idveiculo)
);

-- Inserção de dados na tabela VEICULO
INSERT INTO veiculo (Marca, Modelo, Ano, Placa) 
VALUES
    ('Chevrolet', 'Cobalt', '2022', 'EESS1457'),
    ('Chevrolet', 'Onix', '2022', 'ABDF1457'),
    ('Volkswagen', 'Jetta', '2022', 'CDSD1457'),
    ('Nissan', 'Sentra', '2022', 'EFDS1457'),
    ('Peugeot', '308', '2022', 'EFDF1457'),
    ('Peugeot', '2008', '2022', 'EFGIG1457'),
    ('Nissan', 'Nivus', '2022', 'EDSPH1457'),
    ('Volkswagen', 'Voyage', '2022', 'ESES1457')
;

-- Criação da tabela QUADRODECOLABORADORES
CREATE TABLE quadrodecolaboradores (
    Idmecanicoresponsavel VARCHAR2(10) PRIMARY KEY NOT NULL,
    Nome VARCHAR2(255) NOT NULL,
    Matricula VARCHAR2(100) NOT NULL,
    CPF CHAR(11) NOT NULL,
    Telefone VARCHAR2(45) NOT NULL,
    Especialidade VARCHAR2(255) NOT NULL,
    Endereco VARCHAR2(255) NOT NULL
);

-- Inserção de dados na tabela QUADRODECOLABORADORES
INSERT INTO quadrodecolaboradores (Idmecanicoresponsavel, Nome, Matricula, CPF, Telefone, Especialidade, Endereco)
VALUES
    ('M01', 'Fulano de TAL 1', '5478123', '12457148712', '24978412457', 'Reparos automotivos e Manutenção de Embreagem', 'Rio de Janeiro'),
    ('M02', 'Fulano de TAL 2', '5478122', '54781241021', '24978414457', 'Reparos automotivos e Manutenção de Embreagem', 'Rio de Janeiro'),
    ('M03', 'Fulano de TAL 3', '5478124', '45718451201', '24978415557', 'Reparos automotivos e Manutenção de Embreagem', 'Rio de Janeiro'),
    ('M04', 'Fulano de TAL 4', '5478125', '24157013541', '24978411257', 'Reparos automotivos e Manutenção de Embreagem', 'Rio de Janeiro'),
    ('M05', 'Fulano de TAL 5', '5478126', '54128710241', '24978411157', 'Reparos automotivos e Manutenção de Embreagem', 'Rio de Janeiro'),
    ('M06', 'Fulano de TAL 6', '5478127', '10245871345', '24978411057', 'Reparos automotivos e Manutenção de Embreagem', 'Rio de Janeiro')
;

-- Criação da tabela COLABORADORDISPONIVEL
CREATE TABLE coladoradordisponivel (
    Idequipe VARCHAR2(10) NOT NULL,
    Idmecanicoresponsavel VARCHAR2(10) NOT NULL,
    Idveiculoemmanutencao VARCHAR2(10) NOT NULL,
    PRIMARY KEY (Idequipe, Idmecanicoresponsavel, Idveiculoemmanutencao),
    FOREIGN KEY (Idveiculoemmanutencao) REFERENCES veiculo (Idveiculo),
    FOREIGN KEY (Idmecanicoresponsavel) REFERENCES quadrodecolaboradores (Idmecanicoresponsavel)
);

-- Inserção de dados na tabela COLABORADORDISPONIVEL
INSERT INTO coladoradordisponivel (Idequipe, Idmecanicoresponsavel, Idveiculoemmanutencao)
VALUES
    ('EquipeA', 'M01', '1'),
    ('EquipeA', 'M01', '3'),
    ('EquipeA', 'M02', '2'),
    ('EquipeA', 'M03', '4'),
    ('EquipeA', 'M04', '5'),
    ('EquipeA', 'M05', '6'),
    ('EquipeA', 'M06', '7'),
    ('EquipeA', 'M05', '8')
;

-- Criação da tabela VEICULOEMMANUTENCAO
CREATE TABLE veiculoemmanutencao (
    Idveiculoemmanutencao NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
    Idveiculo NUMBER NOT NULL, 
    Idequipe VARCHAR2(10) NOT NULL, 
    Nomedomecanicoresponsavel VARCHAR2(255) NOT NULL, 
    Iniciodamanutencao DATE NOT NULL, 
    Conclusaodamanutencao DATE, 
    Situacaoatual VARCHAR2(255),
    Tipodereparo VARCHAR2(255), 
    Manutencaoadicional VARCHAR2(255),
    PRIMARY KEY (Idveiculoemmanutencao),
    FOREIGN KEY (Idequipe) REFERENCES coladoradordisponivel (Idequipe),
    FOREIGN KEY (Idveiculo) REFERENCES veiculo (Idveiculo)
);

-- Inserção de dados na tabela VEICULOEMMANUTENCAO
INSERT INTO veiculoemmanutencao (Idveiculo, Idequipe, Nomedomecanicoresponsavel, Iniciodamanutencao, Situacaoatual, Manutencaoadicional)
VALUES 
    (1, 'EquipeA', 'Fulano de Tal 1', TO_DATE('2022-09-15', 'YYYY-MM-DD'), 'Inicio da manutenção em 4 dias', 'não'),
    (2, 'EquipeA', 'Fulano de Tal 1', TO_DATE('2022-09-12', 'YYYY-MM-DD'), 'Inicio da manutenção em 1 dia', 'não'),
    (3, 'EquipeA', 'Fulano de Tal 2', TO_DATE('2022-09-14', 'YYYY-MM-DD'), 'Inicio da manutenção em 3 dias', 'não'),
    (4, 'EquipeA', 'Fulano de Tal 3', TO_DATE('2022-09-15', 'YYYY-MM-DD'), 'Inicio da manutenção em 4 dias', 'não'),
    (5, 'EquipeA', 'Fulano de Tal 4', TO_DATE('2022-09-13', 'YYYY-MM-DD'), 'Inicio da manutenção em 2 dias', 'não'),
    (6, 'EquipeA', 'Fulano de Tal 5', TO_DATE('2022-09-16', 'YYYY-MM-DD'), 'Inicio da manutenção em 5 dias', 'não'),
    (7, 'EquipeA', 'Fulano de Tal 6', TO_DATE('2022-09-13', 'YYYY-MM-DD'), 'Inicio da manutenção em 2 dias', 'não'),
    (8, 'EquipeA', 'Fulano de Tal 5', TO_DATE('2022-09-13', 'YYYY-MM-DD'), 'Inicio da manutenção em 2 dias', 'não')
;


-------
**MYSQL**

-- Criação da tabela CLIENTEPESSOAFISICA
CREATE TABLE clientepessoafisica (
    Idclientepessoafisica INT AUTO_INCREMENT NOT NULL, 
    Nome VARCHAR(255),
    RG CHAR(10) NOT NULL, 
    CPF CHAR(11) NOT NULL,
    Datadenascimento DATE,
    Telefone VARCHAR(45),
    PRIMARY KEY (Idclientepessoafisica),
    UNIQUE (CPF),
    UNIQUE (RG)
);

-- Inserção de dados na tabela CLIENTEPESSOAFISICA
INSERT INTO clientepessoafisica (Nome, RG, CPF, Datadenascimento, Telefone)
VALUES 
    ('Fulado de tal 1', '2654712412', '12457841545', '1992-05-22', '249998-7541'),
    ('Fulado de tal 2', '21456788945', '12456987451', '1990-04-21', '249998-7545'),
    ('Fulado de tal 3', '12457899452', '12459687412', '1991-02-20', '249998-7542'),
    ('Fulado de tal 4', '21469874312', '12456974384', '1995-01-19', '249998-7543')
;

-- Criação da tabela CLIENTEPESSOAJURIDICA
CREATE TABLE clientepessoajuridica (
    Idclientepessoajuridica INT AUTO_INCREMENT NOT NULL, 
    Razaosocial VARCHAR(255),
    Nomefantasia VARCHAR(255),
    CNPJ CHAR(14) NOT NULL,
    Telefone VARCHAR(45),
    PRIMARY KEY (Idclientepessoajuridica),
    UNIQUE (CNPJ)
);

-- Inserção de dados na tabela CLIENTEPESSOAJURIDICA
INSERT INTO clientepessoajuridica (Razaosocial, Nomefantasia, CNPJ, Telefone)
VALUES 
    ('Empresa 1 LTDA', 'Nome Fantasia 1', '12459745123456', '249945-7541'),
    ('Empresa 2 LTDA', 'Nome Fantasia 2', '54789412541021', '249945-5478'),
    ('Empresa 3 LTDA', 'Nome Fantasia 3', '10245789441212','249945-7845')
;

-- Criação da tabela VEICULO
CREATE TABLE veiculo (
    Idveiculo INT AUTO_INCREMENT NOT NULL,
    Marca VARCHAR(255) NOT NULL,
    Modelo VARCHAR(255) NOT NULL,
    Ano CHAR(4),
    Placa VARCHAR(10),
    PRIMARY KEY (Idveiculo)
);

-- Inserção de dados na tabela VEICULO
INSERT INTO veiculo (Marca, Modelo, Ano, Placa) 
VALUES
    ('Chevrolet', 'Cobalt', '2022', 'EESS1457'),
    ('Chevrolet', 'Onix', '2022', 'ABDF1457'),
    ('Volkswagen', 'Jetta', '2022', 'CDSD1457'),
    ('Nissan', 'Sentra', '2022', 'EFDS1457'),
    ('Peugeot', '308', '2022', 'EFDF1457'),
    ('Peugeot', '2008', '2022', 'EFGIG1457'),
    ('Nissan', 'Nivus', '2022', 'EDSPH1457'),
    ('Volkswagen', 'Voyage', '2022', 'ESES1457')
;

-- Criação da tabela QUADRODECOLABORADORES
CREATE TABLE quadrodecolaboradores (
    Idmecanicoresponsavel VARCHAR(10) PRIMARY KEY NOT NULL,
    Nome VARCHAR(255) NOT NULL,
    Matricula VARCHAR(100) NOT NULL,
    CPF CHAR(11) NOT NULL,
    Telefone VARCHAR(45) NOT NULL,
    Especialidade VARCHAR(255) NOT NULL,
    Endereco VARCHAR(255) NOT NULL
);

-- Inserção de dados na tabela QUADRODECOLABORADORES
INSERT INTO quadrodecolaboradores (Idmecanicoresponsavel, Nome, Matricula, CPF, Telefone, Especialidade, Endereco)
VALUES
    ('M01', 'Fulano de TAL 1', '5478123', '12457148712', '24978412457', 'Reparos automotivos e Manutenção de Embreagem', 'Rio de Janeiro'),
    ('M02', 'Fulano de TAL 2', '5478122', '54781241021', '24978414457', 'Reparos automotivos e Manutenção de Embreagem', 'Rio de Janeiro'),
    ('M03', 'Fulano de TAL 3', '5478124', '45718451201', '24978415557', 'Reparos automotivos e Manutenção de Embreagem', 'Rio de Janeiro'),
    ('M04', 'Fulano de TAL 4', '5478125', '24157013541', '24978411257', 'Reparos automotivos e Manutenção de Embreagem', 'Rio de Janeiro'),
    ('M05', 'Fulano de TAL 5', '5478126', '54128710241', '24978411157', 'Reparos automotivos e Manutenção de Embreagem', 'Rio de Janeiro'),
    ('M06', 'Fulano de TAL 6', '5478127', '10245871345', '24978411057', 'Reparos automotivos e Manutenção de Embreagem', 'Rio de Janeiro')
;

-- Criação da tabela COLABORADORDISPONIVEL
CREATE TABLE coladoradordisponivel (
    Idequipe VARCHAR(10) NOT NULL,
    Idmecanicoresponsavel VARCHAR(10) NOT NULL,
    Idveiculoemmanutencao INT NOT NULL,
    PRIMARY KEY (Idequipe, Idmecanicoresponsavel, Idveiculoemmanutencao),
    FOREIGN KEY (Idveiculoemmanutencao) REFERENCES veiculo (Idveiculo),
    FOREIGN KEY (Idmecanicoresponsavel) REFERENCES quadrodecolaboradores (Idmecanicoresponsavel)
);

-- Inserção de dados na tabela COLABORADORDISPONIVEL
INSERT INTO coladoradordisponivel (Idequipe, Idmecanicoresponsavel, Idveiculoemmanutencao)
VALUES
    ('EquipeA', 'M01', 1),
    ('EquipeA', 'M01', 3),
    ('EquipeA', 'M02', 2),
    ('EquipeA', 'M03', 4),
    ('EquipeA', 'M04', 5),
    ('EquipeA', 'M05', 6),
    ('EquipeA', 'M06', 7),
    ('EquipeA', 'M05', 8)
;

-- Criação da tabela VEICULOEMMANUTENCAO
CREATE TABLE veiculoemmanutencao (
    Idveiculoemmanutencao INT AUTO_INCREMENT NOT NULL, 
    Idveiculo INT NOT NULL, 
    Idequipe VARCHAR(10) NOT NULL, 
    Nomedomecanicoresponsavel VARCHAR(255) NOT NULL, 
    Iniciodamanutencao DATE NOT NULL, 
    Conclusaodamanutencao DATE, 
    Situacaoatual VARCHAR(255),
    Tipodereparo VARCHAR(255), 
    Manutencaoadicional VARCHAR(255),
    PRIMARY KEY (Idveiculoemmanutencao),
    FOREIGN KEY (Idequipe) REFERENCES coladoradordisponivel (Idequipe),
    FOREIGN KEY (Idveiculo) REFERENCES veiculo (Idveiculo)
);

-- Inserção de dados na tabela VEICULOEMMANUTENCAO
INSERT INTO veiculoemmanutencao (Idveiculo, Idequipe, Nomedomecanicoresponsavel, Iniciodamanutencao, Situacaoatual, Manutencaoadicional)
VALUES 
    (1, 'EquipeA', 'Fulano de Tal 1', '2022-09-15', 'Inicio da manutenção em 4 dias', 'não'),
    (2, 'EquipeA', 'Fulano de Tal 1', '2022-09-12', 'Inicio da manutenção em 1 dia', 'não'),
    (3, 'EquipeA', 'Fulano de Tal 2', '2022-09-14', 'Inicio da manutenção em 3 dias', 'não'),
    (4, 'EquipeA', 'Fulano de Tal 3', '2022-09-15', 'Inicio da manutenção em 4 dias', 'não'),
    (5, 'EquipeA', 'Fulano de Tal 4', '2022-09-13', 'Inicio da manutenção em 2 dias', 'não'),
    (6, 'EquipeA', 'Fulano de Tal 5', '2022-09-16', 'Inicio da manutenção em 5 dias', 'não'),
    (7, 'EquipeA', 'Fulano de Tal 6', '2022-09-13', 'Inicio da manutenção em 2 dias', 'não'),
    (8, 'EquipeA', 'Fulano de Tal 5', '2022-09-13', 'Inicio da manutenção em 2 dias', 'não')
;

